const express = require('express');
const router = express.Router();
const courseController = require('../controller/course.Controller');
const limit = require('../middleware/limit.middleware');
const { roleAuth ,ROLE} = require('../middleware/auth.middleware');
const { auth } = require('../middleware/auth.middleware');
router.post('/create',limit, courseController.createCourse);
router.get('/all', courseController.getAllCourses);
router.get('/teacher/mycourses', auth, courseController.getAllTeacherCourses);
router.get('/find',auth, courseController.getCourseById);
router.put('/update', auth, roleAuth(ROLE.TEACHER),courseController.updateCourse);
router.delete('/delete', auth, roleAuth(ROLE.TEACHER),courseController.deleteCourse);
module.exports = router;
